global:
  qsname: qs_ansible
  qsenv: dev
  reporting: true
  cis3bucket: s3://quickstart-ci-bucket
  regions:
    - us-east-1
    - us-west-1
    - eu-west-1
    - us-west-2
    - sa-east-1
    - eu-central-1
    - ap-northeast-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-2
 
tests:
  qs_ansiblet1:
    template_file: qs_ansible-example1.template
    parameter_input: qs_ansible-exampleparms1.json
  qs_ansiblet2:
    template_file: qs_ansible-example2.template
    parameter_input: qs_ansible-exampleparms2.json
