global:
  marketplace: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-ansible
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
tests:
  c7:
    parameter_input: Ansible-Tower-c7-QuickStart.json
    template_file: Ansible-Tower-c7-QuickStart.template
  el7:
    parameter_input: Ansible-Tower-el7-QuickStart.json
    regions:
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-2
      - eu-central-1
      - eu-west-1
      - sa-east-1
      - us-east-1
      - us-west-1
      - us-west-2
    template_file: Ansible-Tower-el7-QuickStart.template
