global:
  qsname: quickstart-ansible
  reporting: true
  cis3bucket: s3://quickstart-ci-bucket
  regions:
    - us-east-1
tests:
  centos:
    template_file: Ansible-Tower-c7-QuickStart.template
    parameter_input: Ansible-Tower-c7-QuickStart.json
  rhel:
    template_file: Ansible-Tower-el7-QuickStart.template
    parameter_input: Ansible-Tower-el7-QuickStart.json
