global:
  qsname: qs_ansible
  qsenv: dev
  reporting: true
  cis3bucket: s3://quickstart-ci-bucket
  regions:
    - us-east-1
    - us-west-1
    - eu-west-1
    - us-west-2
    - sa-east-1
    - eu-central-1
    - ap-northeast-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-2
 
tests:
  qs_ansiblet1:
    template_file: Ansible-Tower-QuickStart.template
    parameter_input: Ansible-Tower-QuickStart.json
