global:
  qsname: quickstart-ansible
  reporting: true
  cis3bucket: s3://quickstart-ci-bucket
  regions:
    - us-east-1
    - us-west-1
 
tests:
  ansible-centos:
    template_file: Ansible-Tower-QuickStart.template
    parameter_input: Ansible-Tower-QuickStart.json
  ansible-rhel:
    template_file: Ansible-Tower-el7-QuickStart.template
    parameter_input: Ansible-Tower-el7-QuickStart.json
